steps:
  - name: 'bash'
    args: ['touch', '.env']

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "network",
        "create",
        "eleanor"
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "compose",
        "--project-name=go-common",
        "run",
        "common",
        "go",
        "test",
        "-race",
        "-v",
        "-p",
        "1",
        "./...",
      ]
