version: "3.8"

networks:
  default:
    name: eleanor
    external: true

services:
  common:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env-default
      - .env

  postgres:
    image: postgres:12.3
    ports:
      - 3401:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=go-common
