name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/eleanorhealth/*
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup go
        uses: actions/setup-go@v6.3.0
        with:
          go-version: "^1.26"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0

        with:
          version: latest
          args: -v --timeout 5m --tests=false
