name: vulnerability-scan
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Build the Container image
        run: docker build . --no-cache --file Dockerfile --tag localbuild/testimage:${{ github.sha }}

      - name: Run Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: "localbuild/testimage:${{ github.sha }}"
          trivy-config: ".trivy.yaml"
